[package]
name = "pubmed_db"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
# rusqlite = "0.26.3"
rusqlite = { version = "*", features = ["bundled"] }
# sqlite = "0.26.0"