version: '3.1'

services:

  mongo:
    platform: linux/arm64/v8
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: access
    volumes:
        - /Volumes/JS-EVO970-plus/pubmed/mongo:/data/db
        
  solr:
    platform: linux/arm64/v8
    image: solr:8.11
    restart: always
    ports:
      - 8983:8983
    command:
      - solr-precreate
      - pubmed
    volumes:
        - /Volumes/JS-EVO970-plus/pubmed/solr:/var/solr

networks:
  default:
    external: true
    name: m1-net
