version: '3.1'

services:

  mongo:
    container_name: pubmongo
    env_file:
      - .env
    platform: ${pubmed_db_docker_platform}
    image: mongo:5.0.5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${pubmed_db_mongo_user}
      MONGO_INITDB_ROOT_PASSWORD: ${pubmed_db_mongo_password}
      MONGO_INITDB_DATABASE: ${pubmed_db_mongo_dbname}
    volumes:
        - ${pubmed_db_mongo_dbname}:/data/db
        
# networks:
#   default:
#     external: true
#     name: m1-net
