version: '3.1'

services:
        
  solr:
    container_name: pubsolr
    env_file:
      - .env    
    platform: ${pubmed_db_docker_platform}
    image: solr:8.11
    restart: always
    ports:
      - 8983:8983
    command:
      - solr-precreate
      - pubmed
    volumes:
        - /Volumes/JS-EVO970-plus/pubmed/solr:/var/solr
    
networks:
  default:
    external: true
    name: ${pubmed_db_docker_network}